### ISSUE TITLE
Adding deleted ads to the tap

### ISSUE THREAD

**Issue by TimNg-Pair** [GtheSheep/tap-tiktok#2]
The tap currently doesn't pull in ads that were deleted by default. Can this be added in?

https://ads.tiktok.com/marketing_api/docs?id=1735735588640770

Thanks!

**Comment by GtheSheep** [comment]
Hey @TimNg-Pair - I've opened a PR for this but may need help testing against the API to ensure it works, I have no deleted ads/ groups/ campaigns to test against, could you possibly lend a hand? what's the easiest method to test for you? thanks!

**Comment by TimNg-Pair** [comment]
I found out that the tap wasn't pulling in deleted ads because the total cost from the tap was less than the total cost from TikTok platform UI. I guess a good test would be for me to check if the costs are matching between the tap and the platform.
