### ISSUE TITLE
Due to changes in poetry package, we need to adjust this line to say @main instead of @master

### ISSUE THREAD

**Issue by zachwilner** [GtheSheep/tap-tiktok#8]
https://github.com/GtheSheep/tap-tiktok/blob/591a910f69e4c09df9a30a911fe0857abf874b3c/pyproject.toml#L37

**Comment by zachwilner** [comment]
@GtheSheep

**Comment by GtheSheep** [comment]
This is updated, does it work for you now? 🙂

**Comment by zachwilner** [comment]
Yes!! Thank you and feel better!
